---
# Role install tasks

- name: Create xinetd.d directory
  file:
    path: "{{ xinetd_xinetd_d_path }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - role::xinetd
    - role::xinetd::install
