---
# Role install tasks

- name: Assert distribution is compatible
  assert:
    that: ansible_facts.distribution_major_version is version("8", "<")
    fail_msg: Distribution is not compatible

- name: Create xinetd.d directory
  file:
    path: "{{ xinetd_xinetd_d_path }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - role::xinetd
    - role::xinetd::install
