---
# Role tasks

- name: install xinetd daemon
  include: install.yml
  tags:
    - role::xinetd
    - role::xinetd::install

- name: configure xinetd daemon
  include: configure.yml
  tags:
    - role::xinetd
    - role::xinetd::configure

- name: setup xinetd daemon service
  include: service.yml
  tags:
    - role::xinetd
    - role::xinetd::service
