---
# Role tasks

- name: Install xinetd daemon
  import_tasks: install.yml
  tags:
    - role::xinetd
    - role::xinetd::install

- name: Configure xinetd daemon
  import_tasks: configure.yml
  tags:
    - role::xinetd
    - role::xinetd::configure

- name: Setup xinetd daemon service
  import_tasks: service.yml
  tags:
    - role::xinetd
    - role::xinetd::service
