---
# Role tasks

- name: install xinetd service
  include: install.yml
  tags:
    - role::xinetd
    - role::xinetd::install

- name: configure xinetd service
  include: configure.yml
  tags:
    - role::xinetd
    - role::xinetd::configure
