---
# Role handlers

- name: Reload xinetd
  service:
    name: xinetd
    state: reloaded
  listen:
    - reload xinetd
  tags:
    - role::xinetd
    - role::xinetd::service

- name: Restart xinetd
  service:
    name: xinetd
    state: restarted
  listen:
    - restart xinetd
  tags:
    - role::xinetd
    - role::xinetd::service
