---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - amtega.xinetd
  tasks:
    - name: Test reload handler
      copy:
        content: ""
        dest: /tmp/emptyfile1
        force: no
        mode: 0644
      notify:
        - xinetd reload

    - name: Test restart handler
      copy:
        content: ""
        dest: /tmp/emptyfile2
        force: no
        mode: 0644
      notify:
        - xinetd restart
